import "./globals.css";
import "@picocss/pico/css/pico.min.css";
import styles from "./root.module.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.body}>
        {children}
        <footer className="container">
          ⚛️ Copyright Tom Sherman, {new Date().getFullYear()}.
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
